### ISSUE TITLE
Load/Save Not always work

### ISSUE THREAD

**Issue by mgsx-dev** [b2renger/PdDroidPublisher#1]
Load/Save fail if there's the destination directory doesn't exists.

A workaround is to add a directory savefiles and any file in it to be unzipped in cache directory.

This issue may be obsolete if files are saved in external directory but we have to keep it in mind, maybe SSSAD could create directory structure if needed or maybe we have to do this in java code at first launch.

**Comment by b2renger** [comment]
My opinion is to use external storage to store preset.

We can have factory presets bundled in the apk, and on first install we copy a preset folder on external storage. Usually the content of the sssad folder from the patch. After that the user can save manage his preset as he wants. 

We could also have a button in an android menu to enable the user to restore factory settings and thus recreating the necessary architecture on demand. This will work if the user misplaces the folder and its not found by the app anymore.

**Comment by b2renger** [comment]
decisions have been made, moved to #18
