### ISSUE TITLE
Loadsave abstraction not always detected

### ISSUE THREAD

**Issue by mgsx-dev** [b2renger/PdDroidPublisher#22]
main problem is : 
- 1 GUI patch containing core audio abstraction
- 1 GUI patch standalone

loadsave is included in core audio but not detected by Android

maybe solution is Allow adding non GUI patch in multi view.

**Comment by mgsx-dev** [comment]
Main problem is that sub-abstractions are not parsed for now. This is a limitation todoc : Any widget (including loadsave abstraction) has to be in a root patch to be detected in Android.

**Comment by mgsx-dev** [comment]
non GUI patch is now possible so the workaround/best practice is to have : 
- 2 GUI patches.
- 1 Core patch containing Loadsave abstraction.

**Comment by b2renger** [comment]
documented in the next release of the website
