### ISSUE TITLE
Allow adding non GUI patch in multi view

### ISSUE THREAD

**Issue by mgsx-dev** [b2renger/PdDroidPublisher#23]
Preferable to separate GUI patches from core(s) patches

**Comment by mgsx-dev** [comment]
configuration have now guiPatches and corePatches.

GUI patches are loaded in specified order before Core patches loaded in specified order as well. This choice as been made because open order is important in case of patch interaction during loading (loadbang), for instance when initialize GUI/symbols with messages.

Best practice here would be to define global loading messages (messages for all GUI and core patch) in the last opened core patch.

This behavior is the same as in Pd Desktop : you have to open patches in right order.

This has to be documented for users.

**Comment by b2renger** [comment]
documented in the next version of the website
