### ISSUE TITLE
Samples Patch Tweaking

### ISSUE THREAD

**Issue by mgsx-dev** [b2renger/PdDroidPublisher#40]
This ticket is used to track changes / needs on samples

Wobbler : 
- add master volume
- replace SVG by custom sliders
- replace SSSAD by persist
- stop sound on midi stop (or release sound).

Acid Drum : 
- add mute buttons for each tracks.
- remove audio core from gui and add it as a non gui patch in launcher.

Acid Bass : 
- refactor in three views (Notes, Notes options, Sound)
- add setters for Notes options (popup taplist to set a full line to a specific parameter).
- replace base_note number box by popup taplist with note name and radio button to select octave.
- remove audio core from gui and add it as a non gui patch in launcher.

**Comment by mgsx-dev** [comment]
I'm ok with wobbler now

**Comment by b2renger** [comment]
Sorry for the alpha release delay but I still need some time to add a few more things.

Chorder
- fix load save and reset
- fix initiation

AcidBass
- fix initiation

AcidDrums
-clock seems broken

**Comment by b2renger** [comment]
I'm ok now ! closing it :)
