### ISSUE TITLE
Port custom widget examples from pdpartytest to pd-party net.mgsx.ppp.widget.custom

### ISSUE THREAD

**Issue by b2renger** [b2renger/PdDroidPublisher#41]
this means the deployment of the custom widget library to override components.

every class from net.mgsx.ppp.test.custom should be part of the starter kit.

**Comment by mgsx-dev** [comment]
not sure all of them. When i made them, it was originally to validate override working for all widgets. Some of them could be usefull, some of them not. Some other custom overrides from samples could be shared as well. We have to decide which of them could be shared.

**Comment by b2renger** [comment]
ok so we probably want : 
- CustomBang renamed as SimpleBang
- CustomToggle renamed as SwitchToggle
- RibbonSlider as itself
- CustomSlider renamed as  KnobSlider (to tell people it overrides a slide)
- CustomArray renamed as GridArray
- Taplist is already on

We'll probably want to add your RoundedRadio from the wobbler sample too.
And a custom toggle that fills it's space with a plain color rather thant just a cross.

What do you think ?
