### ISSUE TITLE
Create a visual 1024 x 500 for playstore publication

### ISSUE THREAD

**Issue by b2renger** [b2renger/PdDroidPublisher#45]

**Comment by mgsx-dev** [comment]
3 things are not so good for me : 
- textes are not easy to read
- voice slicer is too white compared to other
- all is very 80's RGB's style (i know samples are like that ;-))

new proposal include in last commit with gimp bitmap effects (blur, saturation, outlines ...)

What do you think ?

**Comment by b2renger** [comment]
ok !
