### ISSUE TITLE
distribution package

### ISSUE THREAD

**Issue by b2renger** [b2renger/PdDroidPublisher#47]
The next release shoud  include abstraction bundle the distribution package.

It should also probably include the tools folder ?

to be cleaner the extracted folder should probably be not called 'eclipse', but rather the name and version of the distrib.

**Comment by mgsx-dev** [comment]
Abstractions are copied to "puredata" folder.

android screen ratio patch is copied from tools to "puredata" folder as well.

Zip extraction seams OK for me : extract here on ubuntu gives a folder named "PdPartyPublisher-x.y.z" containing "eclipse" and "puredata" folder.
