### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mgsx-dev** [b2renger/PdDroidPublisher#51]
put a compatible licence on PPP project : 
- Pd is BSD
- LibPD is BSD as well (copied from Pd)
- Pd4Android has no licence
- DroidParty is GNU (and then not compatible)

Exept DroidParty, best thing would be to copy BSD Pd licence.

**Comment by b2renger** [comment]
At this state lgpl v3 doesn't seem to prevent us from doing what we want, and leaves users do what ever they want. 
Unless, they want to use an external in the app published with this framework ... in this case they'll have to publish the external and its source code bundled with the framework as lgpl v3 aswell
