### ISSUE TITLE
Save not work when values not inited

### ISSUE THREAD

**Issue by mgsx-dev** [b2renger/PdDroidPublisher#7]
This maybe not fixable (SSSAD limitation) but values not initiated will not be saved throw SSSAD.

Scenario : 
- assuming the patch contains a slider without "save"/"initialize" option (and SSSAD mapped properly)
- launch the patch on android or PureData GUI
- save the preset (slider value won't be saved)
- move the slider
- load previously saved preset
- slider is not restored at its initial (saved value) but stay inplace

I think SSSAD need to catch the recorded symbol at least once and maybe there is no other way to do so.

A workaround is to : 
- configure each widget with "initialize at startup" option.
- for non widget values : loadbang symbols at startup.

If this won't be fixed due to SSSAD limitation, at least write it in documentation (limitations / best practice)

**Comment by b2renger** [comment]
Yes you are right this is a "limitation" of sssad. If you don't send at least one value it's indeed not caught. This won't be fixable right now. 

We ought to document this.

For the workarounds we can use init, I would prefer to advise users to build an init by messages with loadbang for all parameters that are saved. Or suggest to load a default preset on startup

**Comment by b2renger** [comment]
We've moved to persist saving system. The issue is still there we just need to document  good practices for this.

**Comment by mgsx-dev** [comment]
new persist library faces the same limitation because of PureData : it would be possible to catch widget value at startup by banging send symbol but this not working for toggle (toggle switch its state when receiving a bang). So, it's impossible to get a symbol value in LibPD nor PureData desktop.

This limitation has to be part of "Patch Preset Documentation"
